version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: adkb
      MYSQL_DATABASE: portfolio
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
    networks:
      - bridged
  
  fastapi:
    image: fastapi:local
    container_name: fastapi
    environment:
      db_host: mysql+pymysql://root:adkb@mysql:3306/portfolio
    ports:
      - 8000:8000
    networks:
      - bridged
  
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - bridged

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - bridged

networks:
  bridged: