version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: adkb
      MYSQL_DATABASE: portfolio
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
    networks:
      - bridged
  
  fastapi:
    image: fastapi:local
    container_name: fastapi
    environment:
      db_host: mysql+pymysql://root:adkb@mysql:3306/portfolio
    ports:
      - 8000:8000
    networks:
      - bridged
  
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'discovery.type=single-node'
    networks:
      - bridged
    volumes:
      - type: bind
        source: esdata
        target: /usr/share/elasticsearch/data

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - bridged
    
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 5602:5602
      - 9201:9201
    volumes:
      - type: bind
        source: nginx
        target: /etc/nginx/conf.d
    networks:
      - bridged

networks:
  bridged: