version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: adkb
      MYSQL_DATABASE: portfolio
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
